### ISSUE TITLE
Make it easier to diagnose errors due to unsigned calls

### ISSUE THREAD

**Issue by nhynes** [oasisprotocol/sapphire-paratime#109]
When a signer is not provided, the call will be sent as unsigned. It's impossible to know whether the called function requires signing, and most don't, so this is a sane fallback. Unfortunately, the error message one receives when it fails is something like `permission denied` or worse, an empty value ("where did my tokens go?"). We should make it easier to notice when this happens.

Suggestions:
* `console.warn` before sending an unsigned call
* analyze the bytecode of the called function and throw an error if the function requires `msg.sender` equality

**Comment by CedarMist** [comment]
Closing this as wontfix, at least not in the client.
