### ISSUE TITLE
Sapphire precompiles in `hardhat node`

### ISSUE THREAD

**Issue by nhynes** [oasisprotocol/sapphire-paratime#110]
One of the benefits of having a Hardhat integration is that we can easily provide a fully featured Sapphire environment, including its precompiles. The precompiles that need to be implemented are (in rough order):

- [ ] `randomBytes`
- [ ] `deriveSymmetricKey`
- [ ] `decrypt`
- [ ] `encrypt`
- [ ] `verifyDigestSignature`
- [ ] `signDigest`

The first three are required by GSN.

**Comment by CedarMist** [comment]
The hardhat node is now deprecated, everybody should be using `sapphire-dev` for localnet deployment.
