### ISSUE TITLE
Sapphire.randomBytes returns zeros on HardHat

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#133]
Hardhat has misleading behavior with Sapphire precompiles.

`staticcall` sets `success=true` even if precompile doesn't exist, and the `bytes memory entropy` returned will not point to real return data (it should return an array of length zero)

Example:

```solidity
// SPDX-License-Identifier: CC-PDDC

pragma solidity ^0.8.0;

contract RandomTest {
    function random()
        external view
        returns (bytes32 a, bytes32 b)
    {
        a = _random_bytes32();

        b = _random_bytes32();
    }

    address internal constant RANDOM_BYTES = 0x0100000000000000000000000000000000000001;

    function _random_bytes32()
        internal view
        returns (bytes32)
    {
        (bool success, bytes memory entropy) = RANDOM_BYTES.staticcall(
            abi.encode(uint256(32), "")
        );
        require( success );
        return bytes32(entropy);
    }
}
```

Test:

```typescript
import { expect } from 'chai';
import { ethers } from "hardhat";
describe('RandomTest', function () {
    it("Multiple calls are all random ", async function () {
        const RandomTest_Contract = await ethers.getContractFactory("RandomTest");
        const rt = await RandomTest_Contract.deploy();
        const resp = await rt.random();
        console.log(resp);
        expect(resp.a).to.not.equal(resp.b);
    });
});
```

If I add `require( entropy.length == 32 );` it fails on hardhat (which is correct), and succeeds on Sapphire (which is also correct).

I suggest making it revert with `error Precompile_Not_Supported();`.

Checking the `chainId` parameter could also work to test for Sapphire precompiles.

-----

The contract can be tested against Sapphire using the sapphire-dev docker container:

  * https://github.com/oasisprotocol/oasis-web3-gateway/pkgs/container/sapphire-dev

e.g. in  hardhat.config.ts use:

```
const TEST_HDWALLET = {
  mnemonic: "test test test test test test test test test test test junk",
  path: "m/44'/60'/0'/0",
  initialIndex: 0,
  count: 20,
  passphrase: "",
};

const config: HardhatUserConfig = {
...
  networks: {
    hardhat: {
      chainId: 1337 // We set 1337 to make interacting with MetaMask simpler
    },
    sapphire_local: {
      url: "http://localhost:8545",
      accounts: TEST_HDWALLET,
      chainId: 0x5afd,
    },
  }
...
```

And run a local Sapphire node with:

    docker run --rm -it -p8545:8545 -p8546:8546 ghcr.io/oasisprotocol/sapphire-dev:latest -to 'test test test test test test test test test test test junk' -n 20

Then run your hardhat tests with:

    pnpm hardhat test --network sapphire_local tests/random.test.ts

**Comment by nhynes** [comment]
This is a problem with all of the precompiles, though. The upcoming hardhat precompiles will fix the problem when sapphire-hardhat is used, though not otherwise, but then that's just due to not following the instructions. I'd say for now we should wait for the hardhat precompiles. If you want, you could add a function like

```solidity
function isSapphire() external view returns (bool) {
    return block.chainid == 0x5aff || block.chainid == 0x5afe;
}
```

and then call that in your contract's constructor
