### ISSUE TITLE
ci: Upgrade to PNPM 8 and Node 18

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#150]
PNPM:
 - There are some minor problems with peer dependencies with PNPM 7, which are resolved by upgrading to PNPM 8
 - 8 is the default version if you install pnpm
 - PNPM 8 also has roughly 2x the number of downloads vs v7, and 7x the number of downloads as v6, so it's safe to say it's the most common version.
 -  PNPM versions: https://www.npmjs.com/package/pnpm?activeTab=versions

NodeJS:
 - Node 16 is in maintainance mode
 - Node 18 is current official LTS version for Docker: https://hub.docker.com/_/node/
 - With PNPM 9, NodeJS 16 will likely be deprecated
 - @types/node v20 is most popular, with v18 2nd popular
 - Node 16 will not be supported in September 2023: https://github.com/nodejs/Release#release-schedule

Generally, targeting TypeScript 5.x usually prefers Node.js v18 or v20, unless we want to target minimal compatible versions in which case TypeScript 5 with Node.js v16 and PNPM 7 is fine for now.

Think it would be good to keep note of supported versions in README.md

**Comment by nhynes** [comment]
I support upgrading pnpm. It's very verbose when it wants an update, so I expect most devs already have it. I've been using it successfully these past few months with sapphire-paratime. Are some other components having a problem?

It's good to support the Node LTSes until they've exited maintenance mode. 16-18 are all pretty compatible. 20 has `fetch` which is going to break `fetchRuntimePublicKey`, but even a light breeze breaks that function, so whatever...

**Comment by CedarMist** [comment]
As per #183 and #177 we've upgraded to PNPM 8 and Node v18
