### ISSUE TITLE
wagmi support

### ISSUE THREAD

**Issue by BerkliumBirb** [oasisprotocol/sapphire-paratime#168]
##### SUMMARY
There's no instruction on how to set up wagmi with sapphire paratime.

##### ISSUE TYPE
- Bug Report

**Comment by BerkliumBirb** [comment]
> sapphire.wrap(window.ethereum)

This won't work for Wallet Connect and others.

> Viem instance

You mean Public Client or Wallet Client? 

I would also note, that in reality it's more crucial to have wrapper around wagmi:Connector's methods [getProvider and getWalletClient](https://github.com/wagmi-dev/wagmi/blob/5e4bc8e26aa9bfc28f654c2d01a38c8d1d7ecc4e/packages/connectors/src/base.ts#L56-L57) because many connectors provide custom ones.

**Comment by rube-de** [comment]
fixed in https://github.com/oasisprotocol/sapphire-paratime/pull/303
