### ISSUE TITLE
contracts: verify multiple accounts can send TEST to each other in e2e tests

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#181]
Need to write an e2e test which verifies that multiple accounts have TEST and can send it to each other.

This will verify that all the accounts provisioned by `sapphire-dev` are functioning correctly.

**Comment by matevz** [comment]
Related oasisprotocol/oasis-web3-gateway#215.

**Comment by aefhm** [comment]
I don't think we need this one anymore based on current monitoring.
