### ISSUE TITLE
Improve JS client testing for subcall delegation

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/sapphire-paratime#195]
##### SUMMARY

Current testing does not delegate an `amount > 0`. Improve this by delegating `100`. Resolve issues with the test.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

JS/TS client Sapphire

https://github.com/oasisprotocol/sapphire-paratime/blob/3a85e42e6c1cc090c28a521cf7df6353aa8a30c8/contracts/test/subcall.ts#L132-L136

**Comment by CedarMist** [comment]
This is implemented in https://github.com/oasisprotocol/sapphire-paratime/pull/202
