### ISSUE TITLE
Error importing JS library in a react TS project

### ISSUE THREAD

**Issue by ismae147** [oasisprotocol/sapphire-paratime#215]
##### SUMMARY
Error importing JS library in a react TS proyect
 

##### ISSUE TYPE
- Bug Report

##### STEPS TO REPRODUCE
1. Install last version of library with yarn  yarn add @oasisprotocol/sapphire-paratime@1.1.3
2. import the library

##### ACTUAL RESULTS

In my react dapp i tried import the JS library 
<img width="1168" alt="image" src="https://github.com/oasisprotocol/sapphire-paratime/assets/9323138/ca2c376d-71b3-4aff-959f-b054a1b59864">
but got that error and this error compiling 
<img width="603" alt="image" src="https://github.com/oasisprotocol/sapphire-paratime/assets/9323138/9f85e15d-a315-4f11-8e0d-2338aca44ef9">

##### EXPECTED RESULTS

Import the library without problems

**Comment by CedarMist** [comment]
Hi @ismae147 

This has been fixed with package 1.1.4

Apologies for the delay
