### ISSUE TITLE
decrypt_into accepts replays.  also next_nonce forces tx/rx to be lockstep synchronous -- is this desirable?

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/sapphire-paratime#3]
https://github.com/oasislabs/sapphire-paratime/blob/4d20964b38ffdded1357823d7987064d0601f7db/encrypting-proxy/src/crypto/cipher.rs#L101

the incr-by-2 odd/even tx/rx nonce design forces messages to be synchronous, so alice send w/ the `tx_nonce` which bob checks is as expected and then bob would send a reply w/ `rx_nonce` which alice checks.  this is okay if synchronous back-and-forth is what we want, but if we may need alice to send 2 messages before getting bob's reply, then it is inconvenient to have a single value where we do `self.nonce.fetch_add(2, SeqCst)`.

instead of the low-order bit denoting whether a number is a tx or rx nonce, we could just use a high order bit.  this looks like a type bit followed by a 63-bit nonce counter space.  or, we could have two separate counters and a "direction" indicator so that messages from alice to bob would not validate as messages from bob to alice (or vice versa).  these are, from a functionality view point, pretty much equivalent (63 bit vs 64 bit nonce space is not a big deal).  granted, we don't have to be starting off viewing things as two separate nonce sequences and a bit to distinguish the direction, since if/when a future change requiring decoupled send/receive functions can separate out the two nonces as suggested, and encode them as 63-nonce plus direction in a wire-format compatible manner, before migrating to allowing a different number of messages being in-flight etc.

anyway, that's the design nit.  it feels weird to me.  it's not wrong, but it feels awkward.

oh, idiomatic rust question.  L103-L107 splits the slices into fields for writing the actual values into, but values are written in L108-L111.  is this idiomatic rust?  i don't like it because i have to ensure that every split slice is actually used -- but maybe the compiler will generate a warning if one field is forgotten and rust programmers habitually rely on that instead?  checking that every field gets initialized is part of audits, obvs, so being able to eyeball that is good, but maybe i'm being old-school and relying on compiler generated errors is better (though being paranoid, i'd prefer to not rely on that solely).

so the code _sends_ both `tx_nonce` and `rx_nonce` when they differ by 1.  which is weird.

in `decrypt_into` L127, no checking of the expected nonce value occurs.  it's used as the input for `open_into` as the expected value _and_ the AAD for AEAD, i believe.  so this is a bug, right?  since there is no checking of the nonce value from `versioned_nonced_tagged_ct` with the `SessionCipher` object's `nonce` member, a `SessionCipher` will accept any replayed message and `decrypt_into` will succeed.

**Comment by nhynes** [comment]
The encrypting proxy has been superseded by client support 🎉 . That makes life simple again! This issue will be reopened if the EP ever comes back.

Thanks for the review.
