### ISSUE TITLE
Why is this function returns a `bind.ContractBackend` instead of `WrappedBackend`? Transactor is not available this way.

### ISSUE THREAD

**Issue by gabkov** [oasisprotocol/sapphire-paratime#320]
https://github.com/oasisprotocol/sapphire-paratime/blob/398f116299fb3bdab421ee81b1e7f0c3aa73136b/clients/go/compat.go#L157

**Comment by aefhm** [comment]
I think returning `WrappedBackend` [there](https://github.com/oasisprotocol/sapphire-paratime/blob/398f116299fb3bdab421ee81b1e7f0c3aa73136b/clients/go/compat.go#L157) makes sense?
cc @matevz

**Comment by matevz** [comment]
Generally you shouldn't need `WrappedBackend` for handling the smart contract (e.g. abigen-generated .go files use `bind.ContractBackend` in their constructor). If you really need sapphire-specific Transactor, you can simply cast it, for example:

```go
backend, err = sapphire.WrapClient(client, func(digest [32]byte) ([]byte, error) {
  return crypto.Sign(digest[:], myKey)
})
sapphireBackend, ok := backend.(*sapphire.WrappedBackend)
txOpts = sapphireBackend.Transactor(c.fromAddress)
fmt.Println(txOpts.GasPrice.String())
```
