### ISSUE TITLE
`_parseCBORUint` failing in `_decodeReceiptUndelegateStart`

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/sapphire-paratime#323]
The `consensusTakeReceiptUndelegateStart` function in `Subcall.sol` is failing on testnet with the `InvalidLength` error.

**Comment by CedarMist** [comment]
The problem it seems was that integers changed from being returned as a bytes array to being an integer.

**Comment by kostko** [comment]
Not sure which fields you mean here, but it depends on how big the integers are. For 128-bit integers we use byte array encoding (as there is no native support), the same as quantities in the consensus layer.

**Comment by CedarMist** [comment]
That'd be the 'epoch' and 'receipt' fields. of delegation & undelegation.

Either way, adding support for uint8, uint16, uint32 & uint64 when decoding has fixed this. If they haven't been changed, then no idea why I only just ran into this now.
