### ISSUE TITLE
docs: Check out EIP-1167 and see how it fits in deployment chapter

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/sapphire-paratime#350]
We got the following question:
> So it seems the contract is not verified, but we use a proxy for it, and the original contract is verified. Does your explorer support verification of proxy? We use the EIP1167 proxy for it. If not, is there a generic interface we could use to interact with the contract?

While the issue is primarily explorer and ABI playground related, it got me thinking why didn't we mention [EIP-1167](https://eips.ethereum.org/EIPS/eip-1167) in the [Deployment](https://docs.oasis.io/dapp/sapphire/deployment) chapter. Explore the EIP, build a minimal example, check out if this pattern can be used on Sapphire and document it.

**Comment by aefhm** [comment]
I tried OpenZeppelin, but that borked. I think I need a different one. https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cae60c595b37b1e7ed7dd50ad0257387ec07c0cf/contracts/proxy/Clones.sol#L6

**Comment by rube-de** [comment]
For me the OZ Clone worked https://github.com/rube-de/sapphire-minimal-proxy

the explorer got updates for it
https://github.com/oasisprotocol/explorer/pull/1538
https://github.com/oasisprotocol/explorer/pull/1540

thou it is only recognized after one transction on the proxy was executed.
with tx: https://explorer.oasis.io/testnet/sapphire/address/0xbA7F3eE55b7939294caFA0F1e096E79722e1BD88
w/o tx: https://explorer.oasis.io/testnet/sapphire/address/0x916336E6d9aE3225dEE3115d7803621022476d0e

**Comment by aefhm** [comment]
Thank @rube-de. Got mine working as well.
