### ISSUE TITLE
docs: Sapphire quickstart guide: vigil.sol and run-vigil.ts links broken 

### ISSUE THREAD

**Issue by CdavM** [oasisprotocol/sapphire-paratime#351]
I have verified that the issue has not been reported yet.

##### SUMMARY

https://github.com/oasisprotocol/sapphire-paratime/blob/main/docs/quickstart.mdx links to vigil.sol and run-vigil.ts, but the links are broken on the main branch.

##### ISSUE TYPE
- Bug Report

**Comment by CdavM** [comment]
Workaround: use an alternative branch like https://github.com/oasisprotocol/sapphire-paratime/blob/CedarMist/wagmi-viem/examples/hardhat/scripts/run-vigil.ts

**Comment by aefhm** [comment]
> Workaround: use an alternative branch like https://github.com/oasisprotocol/sapphire-paratime/blob/CedarMist/wagmi-viem/examples/hardhat/scripts/run-vigil.ts

Agree and thanks for the suggestion! Using this workaround in https://github.com/oasisprotocol/sapphire-paratime/pull/359.

**Comment by aefhm** [comment]
We should also rethink the entire [quick start](https://docs.oasis.io/dapp/sapphire/quickstart) section, but that should be a separate issue/ticket.

**Comment by aefhm** [comment]
Closed by https://github.com/oasisprotocol/sapphire-paratime/pull/378
