### ISSUE TITLE
sapphire-viem-v2: Brave browser default wallet selection unable to override `window.ethereum`

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/sapphire-paratime#386]
##### SUMMARY

Our Viem integration package has usability issue with selection of default Brave wallet.

##### ISSUE TYPE
- Bug Report

##### STEPS TO REPRODUCE

Select Brave wallet as default Brave browser. Navigate to application using `sapphire-viem-v2`.

##### ACTUAL RESULTS

```JavaScript
Uncaught TypeError: Cannot assign to read only property 'ethereum' of object '#<Window>'
    at o (inpage.js:1:31269)
    at r.initializeProvider (inpage.js:1:31747)
    at Object.<anonymous> (inpage.js:1:1116)
    at Object.<anonymous> (inpage.js:1:5585)
    at 1.../../shared/modules/provider-injection (inpage.js:1:5598)
    at i (inpage.js:1:254)
    at e (inpage.js:1:414)
    at inpage.js:1:431
```
Note this is similar to this old [bug](https://github.com/brave/brave-browser/issues/24531), but this Brave wallet [issue](https://github.com/brave/brave-browser/issues/22678) explains that Brave does not want their `window.ethereum` provider to be overriden.

##### EXPECTED RESULTS

Brave user should not be blocked.

**Comment by CedarMist** [comment]
Where are we overriding `window.ethereum` ?

**Comment by aefhm** [comment]
> Where are we overriding `window.ethereum` ?

Correction. We are not. MetaMask is because they like to [override](https://github.com/MetaMask/providers/blob/84452e12d72ed9fa5dc71ab8bed769c507c83f30/src/initializeInpageProvider.ts#L99) things.

This is also not a breaking usability issue because only console developers would see an error. Only #385 was blocking the wallet from loading correctly.

I don't think we need to do anything here.
