### ISSUE TITLE
Improve CI to support UI MetaMask testing

### ISSUE THREAD

**Issue by aefhm** [oasisprotocol/sapphire-paratime#417]
Check out, what's currently hot in the crypto space to for testing your dApp behavior with brave/metamask. Find any relevant sapphire-paratime issues related to this (https://github.com/oasisprotocol/sapphire-paratime/issues/242 ?).

cc the Wallet/dApp team @lubej @lukaw3d

**Comment by lukaw3d** [comment]
I was looking at these to automatically make screenshots in https://github.com/oasisprotocol/dapp-onramp with playwright:
- https://github.com/cawabunga/headless-web3-provider/blob/6bea0e7c72fb07bce4d0ef50149a47762bb5f644/src/wallet/SignMessageMiddleware.ts#L15
- https://github.com/rsksmart/mock-web3-provider/blob/fc4897318246403a179c4fd446bd38e3070ba84e/src/index.ts#L78

**Comment by lukaw3d** [comment]
We test some of ROSE Wallet - Extension with playwright like this:
- https://github.com/oasisprotocol/wallet/blob/e90e33cb5f7535c3504bbf512d18c4544e32cd4d/playwright/utils/extensionTestExtend.ts#L25
- https://github.com/oasisprotocol/wallet/blob/e90e33cb5f7535c3504bbf512d18c4544e32cd4d/playwright/tests/extension.spec.ts#L22

this opens `chrome-extension://ppdadbejkmjnefldpcdjhnkpbjkikoip/popup.2d61f0d3.html` in a tab.
(our ext wallet doesn't need to communicate with any dApps. not sure if that would work)

**Comment by aefhm** [comment]
@matevz mentioned that we ought to incorporate this level of integration testing for `demo-starter` projects so that devs will have a testing framework as a default.
