### ISSUE TITLE
runtime: Enable EIP-1559 support

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/sapphire-paratime#425]
A user asked for EIP-1559 support on [discord](https://discord.com/channels/748635004384313474/960599114993762304/1291369193278668811). It should be supported by the underlying rust-ethereum/evm https://github.com/rust-ethereum/evm/pull/289. Maybe just need to enabled it in the config?

Related https://github.com/oasisprotocol/sapphire-paratime/issues/306

**Comment by kostko** [comment]
This is already enabled in the runtime, we also have tests (there was a bug that was fixed a while back). I think the remaining stuff needs to happen in the Web3 gateway, if anything. cc @ptrus @CedarMist

**Comment by matevz** [comment]
Found it https://github.com/oasisprotocol/oasis-web3-gateway/pull/502
