### ISSUE TITLE
Sapphire hardhat integration state

### ISSUE THREAD

**Issue by chitter99** [oasisprotocol/sapphire-paratime#66]
We would love to start using sapphire in our primary development environment hardhat. I saw there is already an integration with hardhat `@oasisprotocol/sapphire-hardhat` but it doesn't look like it's available on npm yet. When trying it locally, it also seems to have some problems in our configuration. What's the current state of the plugin so far? And when can we expect to start using it? Thanks!

**Comment by nhynes** [comment]
For your hardhatting pleasure [@oasisprotocol/sapphire-hardhat](https://www.npmjs.com/package/@oasisprotocol/sapphire-hardhat). Thanks for reminding me to publish it. Bug reports welcome!

**Comment by chitter99** [comment]
Thanks for the quick release @nhynes, I just tried it out. Unfortunately, the module version specifier for the `@oasisprotocol/sapphire-paratime` module in the hardhat package still uses the `workspace` prefix in the published package. 

https://github.com/oasisprotocol/sapphire-paratime/blob/5d5b9adcb9085145a1c473e010a31bff93732432/integrations/hardhat/package.json#L22

I'm getting the following error when trying to install it from npm.
 
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^1.0.7

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2022-10-05T06_48_55_551Z-debug-0.log
```

Could you republish that via [pnpm pack or publish](https://pnpm.io/workspaces#publishing-workspace-packages)? Thanks for your help!

**Comment by nhynes** [comment]
yep. the `p` was missing. please try `1.0.1`
